import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const userId = 'nlayton'; // Hardcoded for now

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex items-center justify-between px-6 py-4 bg-white border-b border-gray-200 shadow-sm mb-8">
          <div>
            <Link href="/" className="text-2xl font-bold text-blue-700 hover:text-blue-900">Scalar</Link>
          </div>
          <div className="flex gap-6 items-center">
            <span className="text-base font-medium text-gray-400 cursor-not-allowed">Leaderboard</span>
            <span className="text-base font-medium text-gray-400 cursor-not-allowed">Profile</span>
            {userId === 'nlayton' && (
              <Link href="/admin" className="text-base font-medium text-red-700 hover:text-red-900">Admin</Link>
            )}
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
